version: 2
updates:
	- package-ecosystem: "npm"
		directory: "/"
		schedule:
			interval: "daily"
			time: "08:00"
			timezone: "Europe/Paris"
		assignees:
			- "Froggi22"
		open-pull-requests-limit: 10
